baseURL = "/"
languageCode = "en-us"
title = "blinxen's blog"
theme = "re-terminal"
pagination.pagerSize = 1000

[params]
  themeColor = "red"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false

[languages]
  [languages.en.params]
    languageName = "English"
    title = "blinxen's blog"
    owner = "blinxen"
    copyright = "© 2025 blinxen"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "blixnen"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/blinxen"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
